pipeline {
    agent any
    environment{
        DOCKERHUB_CREDS = credentials('dockerhub')
    }
    stages {
        stage("Env Variables") {
            steps {
                echo "The build number is ${env.BUILD_NUMBER}"
            }
        }

         stage('Print Repo') {
            steps {
               echo "The $DOCKERHUB_CREDS_USR = ${env.DOCKERHUB_CREDS_USR}"
            }
         }

        stage('Clone Repo') {
            steps {
                checkout scm
                sh 'ls *'
            }
        }

        stage('Build Image') {
            steps {
                //sh 'docker build -t shanthiravisg/jenkinstest ./pushdockerimage/' (this will use the tag latest)
		        sh 'docker build -t shanthiravisg/jenkinstest:$BUILD_NUMBER ./pushdockerimage/'
            }
        }
    }
}

