pipeline {
    agent any
    environment{
        DOCKERHUB_CREDS = credentials('dockerhub')
    }
    stages {
        stage("Env Variables") {
            steps {
                echo "The build number is ${env.BUILD_NUMBER}"
            }
        }

         stage('Print Repo') {
            steps {
               echo "The $DOCKERHUB_CREDS_USR = ${env.DOCKERHUB_CREDS_USR}"
            }
        }

        stage('Clone Repo') {
            steps {
                checkout scm
                sh 'ls *'
            }
        }
        // stage('Build Image') {
        //     steps {
        //         //sh 'docker build -t shanthiravisg/jenkinstest ./pushdockerimage/' (this will use the tag latest)
		// sh 'docker build -t shanthiravisg/jenkinstest:$BUILD_NUMBER ./pushdockerimage/'
        //     }
        // }
        // stage('Docker Login') {
        //     steps {
        //         //sh 'docker login -u $DOCKERHUB_CREDS_USR -p $DOCKERHUB_CREDS_PSW' (this will leave the password visible)
        //         sh 'echo $DOCKERHUB_CREDS_PSW | docker login -u $DOCKERHUB_CREDS_USR --password-stdin'                
        //         }
        //     }
        // stage('Docker Push') {
        //     steps {
		// //sh 'docker push shanthiravisg/jenkinstest' (this will use the tag latest)    
        //         sh 'docker push shanthiravisg/jenkinstest:$BUILD_NUMBER'
        //         }
        //     }
        }
    post {
		always {
			sh 'docker logout'
		}
	 }
}

