pipeline {
    agent none
    stages {
        stage('Build') {
            agent {
                any {
                    image 'python:2-alpine'
                }
            }
            steps {
                sh 'python -m py_compile pythoncode/add2vals.py pythoncode/calc.py'
                stash(name: 'compiled-results', includes: 'pythoncode/*.py*')
                sh 'ls -l pythoncode'
            }
        }
        stage('Test') { 
            agent {
                any {
                    image 'qnib/pytest' 
                }
            }
            steps {
                sh 'py.test --junit-xml target/test-reports/results.xml pythoncode/test_calc.py' 
                sh 'cat target/test-reports/results.xml'
            }
            post {
                always {
                    junit 'target/test-reports/results.xml' 
                }
            }
        }
    }
}
